<?php
    header("Content-type:text/html;charset=utf-8");

    class a{
        public function K(){echo 'kawaii';}
        public function L(){echo '审核';}
        protected function J(){echo '原始';}

    }

    class b extends a{

    }

    class c extends b{
        function abc(){$this->K();}
    }

    class d extends a{
        function J(){
            echo "全局改写";
        }
        function L(){
            parent::L(); // TODO: Change the autogenerated stub
            echo '<br/>'."改写";
        }
        function K(){
            parent::K(); // TODO: Change the autogenerated stub
            echo '<br/>'."aK";
        }
    }

    echo '多态性'.'<br/>';
    $new = new d;
//    $new ->L();
    $new ->J();

    echo '<hr/>';
    echo '继承性'.'<br/>';
    $obj = new c;
    $obj ->abc();









    die;
    class car{
        public $color = 'red';
        public $wrap;
        static function fire(){
            echo '启动';
        }
    }
    $OBJ = new car;
    var_dump($OBJ);
    echo '<br/>'.$OBJ -> color.'<br/>';
    $OBJ ->color='Black';
    echo $OBJ -> color.'<br/>';
    car::fire();